insert into counter_object values (2, 'RAS');
insert into counter_object values (3, 'Statystyki przydziałów usługi WSMan');
insert into counter_object values (4, 'BranchCache');
insert into counter_object values (5, 'Zasady QoS sieci');
insert into counter_object values (6, 'Udziały klienta SMB');
insert into counter_object values (7, 'SynchronizationNuma');
insert into counter_object values (8, 'Synchronizacja');
insert into counter_object values (9, 'Śledzenie zdarzeń systemu Windows');
insert into counter_object values (10, 'Informacje o strefach termicznych');
insert into counter_object values (11, 'Informacje o procesorze');
insert into counter_object values (12, 'Sesja śledzenia zdarzeń systemu Windows');
insert into counter_object values (13, 'Aktywność systemu plików na dysku');
insert into counter_object values (14, 'Wykorzystanie EC bezpośredniej transmisji pakietów');
insert into counter_object values (15, 'Aktywność funkcji RDMA');
insert into counter_object values (16, 'Liczniki bezpośredniego odbierania pakietów');
insert into counter_object values (17, 'Głębokość kolejki PacketDirect');
insert into counter_object values (18, 'Cykle aktywności sieciowej na procesor');
insert into counter_object values (19, 'Aktywność karty sieciowej na procesor');
insert into counter_object values (20, 'Aktywność fizycznej karty sieciowej');
insert into counter_object values (21, 'Liczniki bezpośredniej transmisji pakietów');
insert into counter_object values (22, 'Filtry bezpośredniego odbierania pakietów');
insert into counter_object values (23, 'Tabela routingu rozproszonego');
insert into counter_object values (24, 'XHCI CommonBuffer');
insert into counter_object values (25, 'XHCI TransferRing');
insert into counter_object values (26, 'XHCI Interrupter');
insert into counter_object values (27, 'Netlogon');
insert into counter_object values (28, 'Serwer SMB');
insert into counter_object values (29, 'Sesje serwera SMB');
insert into counter_object values (30, 'Udziały serwera SMB');
insert into counter_object values (31, 'Funkcja RemoteFX - sieć');
insert into counter_object values (32, 'Grafika RemoteFX');
insert into counter_object values (33, 'Windows Media Player Metadata');
insert into counter_object values (34, 'PowerShell Workflow');
insert into counter_object values (35, 'Usługa HTTP');
insert into counter_object values (36, 'Grupy adresów URL usługi HTTP');
insert into counter_object values (37, 'Kolejki żądań usługi HTTP');
insert into counter_object values (38, 'Diagnostyka wydajności protokołu TCPIP');
insert into counter_object values (39, 'Miernik energii');
insert into counter_object values (40, 'Rój optymalizacji dostarczania');
insert into counter_object values (41, 'ServiceModelEndpoint 4.0.0.0');
insert into counter_object values (42, 'ServiceModelOperation 4.0.0.0');
insert into counter_object values (43, 'ServiceModelService 4.0.0.0');
insert into counter_object values (44, 'Classification Engine: Content Analysis Session');
insert into counter_object values (45, 'Classification Engine: Rule Package Cache');
insert into counter_object values (46, 'Pamięć dynamiczna funkcji Hyper-V - usługa integracji');
insert into counter_object values (47, 'Klient Teredo');
insert into counter_object values (48, 'Serwer Teredo');
insert into counter_object values (49, 'IPHTTPS - globalne');
insert into counter_object values (50, 'Globalna usługa DNS64');
insert into counter_object values (51, 'Sesja IPHTTPS');
insert into counter_object values (52, 'Przekaźnik Teredo');
insert into counter_object values (53, 'Buforowanie po stronie klienta');
insert into counter_object values (54, 'Pliki trybu offline');
insert into counter_object values (55, 'Hyper-V Virtual Machine Bus Pipes');
insert into counter_object values (56, 'Warstwa miejsc do magazynowania');
insert into counter_object values (57, 'Bufor zapisu miejsc do magazynowania');
insert into counter_object values (58, 'BitLocker');
insert into counter_object values (59, 'Podstawowy dostawca usługi Microsoft Winsock');
insert into counter_object values (60, 'Usługa faksowania');
insert into counter_object values (61, 'Authorization Manager Applications');
insert into counter_object values (62, 'Protokół rozpoznawania nazw równorzędnych');
insert into counter_object values (63, 'WFPv6');
insert into counter_object values (64, 'WFP');
insert into counter_object values (65, 'Sterownik IPsec');
insert into counter_object values (66, 'IPsec IKEv1 IPv6');
insert into counter_object values (67, 'IPsec IKEv1 IPv4');
insert into counter_object values (68, 'WFPv4');
insert into counter_object values (69, 'IPsec IKEv2 IPv6');
insert into counter_object values (70, 'IPsec AuthIP IPv6');
insert into counter_object values (71, 'Połączenia IPsec');
insert into counter_object values (72, 'IPsec AuthIP IPv4');
insert into counter_object values (73, 'IPsec IKEv2 IPv4');
insert into counter_object values (74, 'Rodzajowe protokoły IKEv1, AuthIP i IKEv2');
insert into counter_object values (75, 'Potok modułu taktującego');
insert into counter_object values (76, 'Przepływ modułu taktującego');
insert into counter_object values (77, 'Usługi terminalowe');
insert into counter_object values (78, 'WorkflowServiceHost 4.0.0.0');
insert into counter_object values (79, 'Urządzenie maszyny wirtualnej klienta VSC syntetycznego kontrolera 3D funkcji RemoteFX');
insert into counter_object values (80, 'Kanał transportu maszyny wirtualnej klienta VSC syntetycznego kontrolera 3D funkcji RemoteFX');
insert into counter_object values (81, 'Dane środowiska CLR technologii .NET');
insert into counter_object values (82, 'Obsługa sieci .NET CLR');
insert into counter_object values (83, 'Obsługa sieci .NET CLR 4.0.0.0');
insert into counter_object values (84, '.NET Data Provider for MySQL');
insert into counter_object values (85, 'Dostawca danych technologii .NET dla oprogramowania firmy Oracle');
insert into counter_object values (86, 'Dostawca danych technologii .NET dla serwera SQL');
insert into counter_object values (87, 'MSDTC Bridge 3.0.0.0');
insert into counter_object values (88, 'Pamięć .NET CLR');
insert into counter_object values (89, 'Współdziałanie .NET CLR');
insert into counter_object values (90, 'Wyjątki .NET CLR');
insert into counter_object values (91, 'Ładowanie .NET CLR');
insert into counter_object values (92, 'Blokady i wątki .NET CLR');
insert into counter_object values (93, 'Kompilator JIT dla .NET CLR');
insert into counter_object values (94, 'Usługi zdalne .NET CLR');
insert into counter_object values (95, 'Zabezpieczenia .NET CLR');
insert into counter_object values (96, 'ASP.NET');
insert into counter_object values (97, 'Aplikacje ASP.NET');
insert into counter_object values (98, 'ASP.NET w wersji 4.0.30319');
insert into counter_object values (99, 'Aplikacje ASP.NET w wersji 4.0.30319');
insert into counter_object values (100, 'Usługa stanu ASP.NET');
insert into counter_object values (101, 'Baza danych');
insert into counter_object values (102, 'Baza danych ==> Klasy tabeli');
insert into counter_object values (103, 'Baza danych ==> Wystąpienia');
insert into counter_object values (104, 'MSDTC Bridge 4.0.0.0');
insert into counter_object values (105, 'ServiceModelEndpoint 3.0.0.0');
insert into counter_object values (106, 'Dysk logiczny');
insert into counter_object values (107, 'Dysk fizyczny');
insert into counter_object values (108, 'Readresator');
insert into counter_object values (109, 'Przeglądarka');
insert into counter_object values (110, 'Pamięć podręczna');
insert into counter_object values (111, 'Procesor');
insert into counter_object values (112, 'Pamięć');
insert into counter_object values (113, 'Obiekty');
insert into counter_object values (114, 'Plik stronicowania');
insert into counter_object values (115, 'System');
insert into counter_object values (116, 'Pamięć węzła NUMA');
insert into counter_object values (117, 'Proces');
insert into counter_object values (118, 'Wątek');
insert into counter_object values (119, 'Obiekt zadania');
insert into counter_object values (120, 'Szczegóły obiektu zadania');
insert into counter_object values (121, 'Pamięć podręczna funkcji ReadyBoost');
insert into counter_object values (122, 'Port RAS');
insert into counter_object values (123, 'Całkowita liczba połączeń RAS');
insert into counter_object values (124, 'ServiceModelOperation 3.0.0.0');
insert into counter_object values (125, 'ServiceModelService 3.0.0.0');
insert into counter_object values (126, 'SMSvcHost 3.0.0.0');
insert into counter_object values (127, 'SMSvcHost 4.0.0.0');
insert into counter_object values (128, 'Windows Workflow Foundation');
insert into counter_object values (129, 'Kolejka wydruku');
insert into counter_object values (130, 'Telefonia');
insert into counter_object values (131, 'Połączenie NBT');
insert into counter_object values (132, 'Interfejs sieciowy');
insert into counter_object values (133, 'Karta sieciowa');
insert into counter_object values (134, 'IPv4');
insert into counter_object values (135, 'Protokół ICMP');
insert into counter_object values (136, 'TCPv4');
insert into counter_object values (137, 'UDPv4');
insert into counter_object values (138, 'IPv6');
insert into counter_object values (139, 'ICMPv6');
insert into counter_object values (140, 'TCPv6');
insert into counter_object values (141, 'UDPv6');
insert into counter_object values (142, 'USB');
insert into counter_object values (143, 'WF  4.0.0.0');
insert into counter_object values (144, 'Indeksator wyszukiwania');

commit;